model:
  n_embd: 512
  n_attn: 8
  n_head: 8
  ctx_len: 512
  rwkv_emb_scale: 1.0
  rwkv_tiny_attn: 64
  rwkv_tiny_head: 2
  n_ffn: 1024
  n_layer: 8
  patch_size: 20
  n_classes: 2
  resolution: [600, 400]
  scale_init: 0
  mlp_head: True
  mean: False
  pos_enc: True
  block: "rwkv" #former rwkv, can decide between "rwkv", "transformer", "identity"  (set resnet = True if identity selected)
  resnet: True
training:
  batch_size: 64
  log_n: 50
  train_data_dir: "data/SN/train"
  val_data_dir: "data/SN/valid"
  test_data_dir: "data/SN/test"
  num_epochs: 5
  warmup_epochs: 1
  max_epochs: 5
  warmup_factor: 0.1
  batch_size_val: 64
  lr: 0.0008 # default adam is 0.00000001
  #Default config not necessary
