model:
  n_embd: 768
  n_attn: 10
  n_head: 10
  ctx_len: 512
  rwkv_emb_scale: 1.0
  rwkv_tiny_attn: 64
  rwkv_tiny_head: 2
  n_ffn: 768
  n_layer: 6
  patch_size: 20
  n_classes: 7
  resolution: [600, 400]
  scale_init: 0
  mean : False
  pos_enc : True
  block : "rwkv" 
  resnet : True
  mlp_head: True
training:
  batch_size : 64
  log_n : 50
  train_data_dir : 'data/CAER-S/train'
  val_data_dir : 'data/CAER-S/valid'
  test_data_dir : 'data/CAER-S/test'
  num_epochs : 20
  warmup_epochs : 1
  max_epochs : 20
  warmup_factor : 0.1
  batch_size_val : 64
  lr : 0.001
  #Failed experiment too large to train